title: LLM Compressor Tutorial
description: A tutorial for LLM Compressor, built with agentic AI.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Source Repository: https://github.com/Chr1st1anSears/agentic-llm-comp-docs

# Mermaid settings
mermaid:
  version: "11.6.0"  # Pick the version you want
  # Default configuration
  config: |
    directionLR
